export const articles = [
    {
        id: 28,
        slug: "zero-latency-infrastructure-ochat",
        title: "Achieving Zero Latency: The O-Chat Global Infrastructure",
        excerpt: "A deep dive into how O-Chat utilizes Edge Computing and optimized routing to deliver messages in under 50ms, regardless of where users are located.",
        category: "Engineering",
        tag: "Technical",
        author: { name: "Luca Moretti", avatar: "https://i.pravatar.cc/40?img=12" },
        date: "2025-03-01",
        readTime: "10 min read",
        // Updated cover image to better reflect global network infrastructure
        coverImage: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80",
        views: 8942,
        likes: 645,
        featured: true,
    },
    {
        id: 29,
        slug: "quantum-resistant-encryption-future",
        title: "Beyond E2EE: Preparing O-Chat for Quantum-Resistant Security",
        excerpt: "Encryption standards are changing. Learn how O-Chat is implementing post-quantum cryptography to ensure your private conversations remain secure for decades.",
        category: "Security",
        tag: "Deep Dive",
        author: { name: "Sophie Durand", avatar: "https://i.pravatar.cc/40?img=23" },
        date: "2025-03-05",
        readTime: "9 min read",
        // Updated cover image to have a more futuristic, quantum-computing vibe
        coverImage: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=800&q=80",
        views: 4210,
        likes: 312,
        featured: false,
    },
    {
        id: 30,
        slug: "real-time-translation-ai-ochat",
        title: "Breaking Language Barriers with O-Chat Real-Time Translation",
        excerpt: "Communicate with anyone, anywhere. Discover the neural machine translation models that power O-Chat’s seamless, instant multilingual messaging.",
        category: "AI & Technology",
        tag: "Trending",
        author: { name: "Aria Chen", avatar: "https://i.pravatar.cc/40?img=47" },
        date: "2025-03-10",
        readTime: "7 min read",
        coverImage: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80",
        views: 12450,
        likes: 982,
        featured: true,
    },
    {
        id: 31,
        slug: "sharding-billions-of-messages",
        title: "Sharding the Stream: How O-Chat Manages Billions of Messages",
        excerpt: "Scaling a database for real-time chat is a nightmare. This article explains our horizontal sharding strategy for maintaining performance at massive scale.",
        category: "Engineering",
        tag: "Advanced",
        author: { name: "Luca Moretti", avatar: "https://i.pravatar.cc/40?img=12" },
        date: "2025-03-14",
        readTime: "11 min read",
        coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80",
        views: 3102,
        likes: 245,
        featured: false,
    },
    {
        id: 32,
        slug: "biometric-auth-messaging-security",
        title: "Biometric Authentication: Securing O-Chat on Mobile",
        excerpt: "Why FaceID and Fingerprint sensors are becoming the primary gatekeepers for private messaging apps and how O-Chat implements them securely.",
        category: "Security",
        tag: "New",
        author: { name: "Elias Brandt", avatar: "https://i.pravatar.cc/40?img=68" },
        date: "2025-03-18",
        readTime: "6 min read",
        coverImage: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&q=80",
        views: 5677,
        likes: 421,
        featured: false,
    },
    {
        id: 33,
        slug: "adaptive-ui-chat-personalization",
        title: "Adaptive UI: The Next Frontier in O-Chat User Experience",
        excerpt: "Interface design that learns from you. Exploring how O-Chat uses machine learning to suggest the best layout and tools based on your chat habits.",
        category: "Design",
        tag: "Insights",
        author: { name: "Nadia Vasquez", avatar: "https://i.pravatar.cc/40?img=56" },
        date: "2025-03-22",
        readTime: "8 min read",
        coverImage: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80",
        views: 4890,
        likes: 356,
        featured: true,
    },
    {
        id: 34,
        slug: "building-custom-ochat-bots",
        title: "Tutorial: Building Your First Custom Bot for the O-Chat Ecosystem",
        excerpt: "A complete developer's guide to using the O-Chat SDK to build automated assistants, customer support bots, and productivity tools.",
        category: "Tutorial",
        tag: "Technical",
        author: { name: "Kai Nakamura", avatar: "https://i.pravatar.cc/40?img=33" },
        date: "2025-03-25",
        readTime: "15 min read",
        coverImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80",
        views: 7321,
        likes: 589,
        featured: false,
    },
    {
        id: 35,
        slug: "voice-ai-noise-cancellation",
        title: "Crystal Clear: AI-Powered Noise Cancellation in O-Chat Voice",
        excerpt: "How we use deep learning models to isolate voices and eliminate background noise during O-Chat voice calls in loud environments.",
        category: "AI & Technology",
        tag: "Popular",
        author: { name: "Aria Chen", avatar: "https://i.pravatar.cc/40?img=47" },
        date: "2025-03-28",
        readTime: "9 min read",
        coverImage: "https://images.unsplash.com/photo-1589254065878-42c9da997008?w=800&q=80",
        views: 6100,
        likes: 472,
        featured: false,
    },
    {
        id: 36,
        slug: "data-sovereignty-enterprise-chat",
        title: "Data Sovereignty: Why Enterprise O-Chat Users Choose Self-Hosting",
        excerpt: "For organizations that need absolute control. Understanding O-Chat's hybrid cloud and on-premise solutions for high-security enterprise environments.",
        category: "Security",
        tag: "Must Read",
        author: { name: "Sophie Durand", avatar: "https://i.pravatar.cc/40?img=23" },
        date: "2025-04-01",
        readTime: "10 min read",
        coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
        views: 3912,
        likes: 288,
        featured: false,
    },
];


